import React from "react";
import Head from "next/head";

import styles from '../../styles/Home.module.css'
import Link from "next/link";

export interface PageLayoutInterface {
  title?: string
  children?: React.ReactNode
}

const PageLayout: React.FC<PageLayoutInterface> = ({ children, title='News-App' }) => {
  return (
    <>
      <Head>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
        <title>{title}</title>
      </Head>
      <header className={styles.header}>
        <div>
          <Link href='/'>
            🗞️ News App
          </Link>
        </div>
        <div>
          <Link href='/about'>About</Link>
        </div>
      </header>
      <main>
        {children}
      </main>
    </>
  )
};

export default PageLayout;